spring:
  application:
    name: cosy-domain-provider
  datasource:
    url: jdbc:postgresql://localhost:5432/cosy
    username: cosy
    password: cosy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


aws:
  region: eu-central-1
  route53:
    hosted-zone-id: ${AWS_HOSTED_ZONE_ID}
    domain: ${AWS_DOMAIN}
    default-ttl: 300

jwt:
  secret-key: ${COSY_DOMAIN_PROVIDER_JWT_SECRET_KEY:e8996bf24977ce5615015c717447911799207025d1998a01256b7b7717bac18e} #change in prod
  identity-token-expiration-time: 3600000 #1 hour
  refresh-token-expiration-time: 2678400000 #1 month
