spring:
  application:
    name: cosy-domain-provider
  datasource:
    url: jdbc:postgresql://localhost:5432/cosy
    username: cosy
    password: cosy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


aws:
  region: eu-central-1
  route53:
    hosted-zone-id: ${AWS_HOSTED_ZONE_ID}
    domain: ${AWS_DOMAIN}
    default-ttl: 300
